const demoText = "DEMO DATA — NOT OFFICIAL GOVERNMENT DATA";

export const adminContentResources = {
  hostels: {
    title: "Hostels",
    description:
      "Manage hostel directory entries. Deleting a hostel deactivates it to preserve application references.",
    fields: [
      { key: "code", label: "Code", type: "text", required: true },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "address", label: "Address", type: "textarea" },
      { key: "capacity", label: "Capacity", type: "number", min: 0 },
      { key: "isActive", label: "Active", type: "checkbox" },
      { key: "isDemo", label: demoText, type: "checkbox", demo: true },
    ],
    columns: ["code", "name", "address", "capacity", "isActive", "isDemo"],
    defaults: {
      code: "",
      name: "",
      description: "",
      address: "",
      capacity: "",
      isActive: true,
      isDemo: true,
    },
  },
  facilities: {
    title: "Facilities",
    description:
      "Maintain the facility directory shown with hostel information.",
    fields: [
      { key: "code", label: "Code", type: "text", required: true },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "isDemo", label: demoText, type: "checkbox", demo: true },
    ],
    columns: ["code", "name", "description", "isDemo"],
    defaults: { code: "", name: "", description: "", isDemo: true },
  },
  fees: {
    title: "Fees",
    description: "Manage active fee schedules and their effective dates.",
    fields: [
      { key: "hostelId", label: "Hostel", type: "hostel" },
      { key: "feeCode", label: "Fee code", type: "text", required: true },
      {
        key: "description",
        label: "Description",
        type: "text",
        required: true,
      },
      {
        key: "amount",
        label: "Amount",
        type: "number",
        min: 0,
        step: "0.01",
        required: true,
      },
      {
        key: "currency",
        label: "Currency (ISO code)",
        type: "text",
        maxLength: 3,
        required: true,
      },
      {
        key: "effectiveFrom",
        label: "Effective from",
        type: "date",
        required: true,
      },
      { key: "effectiveTo", label: "Effective to", type: "date" },
      { key: "isActive", label: "Active", type: "checkbox" },
      { key: "isDemo", label: demoText, type: "checkbox", demo: true },
    ],
    columns: [
      "feeCode",
      "description",
      "amount",
      "currency",
      "effectiveFrom",
      "effectiveTo",
      "isActive",
      "isDemo",
    ],
    defaults: {
      hostelId: "",
      feeCode: "",
      description: "",
      amount: "",
      currency: "USD",
      effectiveFrom: "",
      effectiveTo: "",
      isActive: true,
      isDemo: true,
    },
  },
  notices: {
    title: "Notices",
    description:
      "Draft, publish, archive, or remove public notices. Published notices are visible on the public site.",
    fields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "body", label: "Notice body", type: "textarea", required: true },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: ["draft", "published", "archived"],
      },
      { key: "expiresAt", label: "Expires at", type: "datetime" },
      { key: "isDemo", label: demoText, type: "checkbox", demo: true },
    ],
    columns: ["title", "status", "expiresAt", "isDemo"],
    defaults: {
      title: "",
      body: "",
      status: "draft",
      expiresAt: "",
      isDemo: true,
    },
  },
  rules: {
    title: "Rules",
    description:
      "Manage rule text and effective periods. Only published rules in date range appear publicly.",
    fields: [
      { key: "ruleCode", label: "Rule code", type: "text", required: true },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "body", label: "Rule text", type: "textarea", required: true },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: ["draft", "published", "archived"],
      },
      { key: "effectiveFrom", label: "Effective from", type: "date" },
      { key: "effectiveTo", label: "Effective to", type: "date" },
      { key: "isDemo", label: demoText, type: "checkbox", demo: true },
    ],
    columns: [
      "ruleCode",
      "title",
      "status",
      "effectiveFrom",
      "effectiveTo",
      "isDemo",
    ],
    defaults: {
      ruleCode: "",
      title: "",
      body: "",
      status: "draft",
      effectiveFrom: "",
      effectiveTo: "",
      isDemo: true,
    },
  },
  "important-dates": {
    title: "Important Dates",
    description:
      "Maintain admission-year event dates. Only published dates are shown publicly.",
    fields: [
      {
        key: "admissionYear",
        label: "Admission year",
        type: "number",
        min: 1900,
        max: 2200,
        required: true,
      },
      { key: "eventCode", label: "Event code", type: "text", required: true },
      { key: "title", label: "Event", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "startsAt", label: "Starts at", type: "datetime" },
      { key: "endsAt", label: "Ends at", type: "datetime" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: ["draft", "published", "archived"],
      },
      { key: "isDemo", label: demoText, type: "checkbox", demo: true },
    ],
    columns: [
      "admissionYear",
      "eventCode",
      "title",
      "startsAt",
      "endsAt",
      "status",
      "isDemo",
    ],
    defaults: {
      admissionYear: new Date().getFullYear(),
      eventCode: "",
      title: "",
      description: "",
      startsAt: "",
      endsAt: "",
      status: "draft",
      isDemo: true,
    },
  },
  settings: {
    title: "Settings",
    description:
      "Manage portal settings and JSON page content. Public page keys use the format public_page:<page-slug> and require Public visibility.",
    fields: [
      { key: "key", label: "Setting key", type: "text", required: true },
      { key: "value", label: "Value (JSON)", type: "json", required: true },
      { key: "isPublic", label: "Publicly readable", type: "checkbox" },
      { key: "isDemo", label: demoText, type: "checkbox", demo: true },
    ],
    columns: ["key", "value", "isPublic", "isDemo"],
    defaults: { key: "", value: "{}", isPublic: false, isDemo: true },
  },
};
